# Generated by Django 5.2.4 on 2025-07-28 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 28, 17, 15, 8, 658374, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
