# Generated by Django 5.2.4 on 2025-07-28 17:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_remove_card_image_cardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='CardImage',
        ),
    ]
